/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as DestinosIndexRouteImport } from './routes/destinos.index'
import { Route as DestinosSlugRouteImport } from './routes/destinos.$slug'
import { Route as RoteirosIndexRouteImport } from './routes/roteiros.index'
import { Route as RoteirosSlugRouteImport } from './routes/roteiros.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosIndexRoute = DestinosIndexRouteImport.update({
  id: '/destinos/',
  path: '/destinos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosSlugRoute = DestinosSlugRouteImport.update({
  id: '/destinos/$slug',
  path: '/destinos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosIndexRoute = RoteirosIndexRouteImport.update({
  id: '/roteiros/',
  path: '/roteiros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteirosSlugRoute = RoteirosSlugRouteImport.update({
  id: '/roteiros/$slug',
  path: '/roteiros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experiencias': typeof ExperienciasRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/destinos/': typeof DestinosIndexRoute
  '/roteiros/': typeof RoteirosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experiencias': typeof ExperienciasRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/destinos': typeof DestinosIndexRoute
  '/roteiros': typeof RoteirosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experiencias': typeof ExperienciasRoute
  '/destinos/$slug': typeof DestinosSlugRoute
  '/roteiros/$slug': typeof RoteirosSlugRoute
  '/destinos/': typeof DestinosIndexRoute
  '/roteiros/': typeof RoteirosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experiencias'
    | '/destinos/$slug'
    | '/roteiros/$slug'
    | '/destinos/'
    | '/roteiros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experiencias'
    | '/destinos/$slug'
    | '/roteiros/$slug'
    | '/destinos'
    | '/roteiros'
  id:
    | '__root__'
    | '/'
    | '/experiencias'
    | '/destinos/$slug'
    | '/roteiros/$slug'
    | '/destinos/'
    | '/roteiros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienciasRoute: typeof ExperienciasRoute
  DestinosSlugRoute: typeof DestinosSlugRoute
  RoteirosSlugRoute: typeof RoteirosSlugRoute
  DestinosIndexRoute: typeof DestinosIndexRoute
  RoteirosIndexRoute: typeof RoteirosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos/': {
      id: '/destinos/'
      path: '/destinos'
      fullPath: '/destinos/'
      preLoaderRoute: typeof DestinosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos/$slug': {
      id: '/destinos/$slug'
      path: '/destinos/$slug'
      fullPath: '/destinos/$slug'
      preLoaderRoute: typeof DestinosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/': {
      id: '/roteiros/'
      path: '/roteiros'
      fullPath: '/roteiros/'
      preLoaderRoute: typeof RoteirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiros/$slug': {
      id: '/roteiros/$slug'
      path: '/roteiros/$slug'
      fullPath: '/roteiros/$slug'
      preLoaderRoute: typeof RoteirosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienciasRoute: ExperienciasRoute,
  DestinosSlugRoute: DestinosSlugRoute,
  RoteirosSlugRoute: RoteirosSlugRoute,
  DestinosIndexRoute: DestinosIndexRoute,
  RoteirosIndexRoute: RoteirosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
